baseURL = "https://rogueliketutorials.com/"
languageCode = "en-us"
title = "Roguelike Tutorials"
theme = "hugo-coder"
enableEmoji = true

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[languages.en]
  languageName = "English"

  copyright = "Last updated July 7th, 2020"

  [[languages.en.menu.main]]
    url = "/"
    name = "Home"
    weight = 1
  [[languages.en.menu.main]]
    url = "tutorials/tcod/v2/"
    name = "TCOD Tutorial (2020)"
    weight = 2
  [[languages.en.menu.main]]
    url = "tutorials/tcod/2019/"
    name = "TCOD Tutorial (2019)"
    weight = 3
  [[languages.en.menu.main]]
    url = "about/"
    name = "About"
    weight = 4

[params]
  mainSections = ["post"]
  colorScheme = "dark"
  hidecolorschemetoggle = false

  hidecredits = true
  hidecopyright = true

  customCSS = ["css/style.css"]
  customJS = ["js/codetabs.js"]

  [params.sidebar]
    showRecent = false

  [params.header]
    colorScheme = "dark"
