baseURL = "http://rogueliketutorials.com/"
languageCode = "en-us"
title = "Roguelike Tutorials"

theme = "bootstrap"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

[languages.en]
  languageName = "English"

  copyright = "Last updated July 7th, 2020"

  [[languages.en.menu.main]]
    url = "/"
    name = "Home"
    weight = 1
  [[languages.en.menu.main]]
    url = "/tutorials/tcod/v2/"
    name = "TCOD Tutorial (New)"
    weight = 2
  [[languages.en.menu.main]]
    url = "/tutorials/tcod/"
    name = "TCOD Tutorial (Old)"
    weight = 2
  [[languages.en.menu.main]]
    url = "/about/"
    name = "About"
    weight = 3

[params]
  mainSections = ["post"]

  [params.sidebar]
    showRecent = false
  
  [params.header]
    colorScheme = "dark"
