baseURL = "http://rogueliketutorials.com/"
languageCode = "en-us"
title = "Roguelike Tutorials"

theme = "bootstrap"

[params]
  mainSections = ["post"]

  [params.sidebar]
    showRecent = false
  
  [params.header]
    colorScheme = "dark"